############################################################
# 1. GEOMETRY
############################################################

# World volume filled with Air
/musr/command construct box World 1000 1000 1500 Air 0 0 0 no_logical_volume norot dead 0



# back streem detectors
/musr/command construct box Det0 20 20 0.1 G4_Si 0 0 -40 log_World norot musr/ScintSD 100
/musr/command construct box Det1 20 20 0.1 G4_Si 0 0 -20 log_World norot musr/ScintSD 101

# Special name Target -> muTarget* variables stored automatically
/musr/command construct tubs Target 0 10 2 0 360 G4_Cu 0 0 0 log_World norot dead 10


/musr/command construct box Det2 20 20 0.1 G4_Si 0 0 20 log_World norot musr/ScintSD 102
/musr/command construct box Det3 20 20 0.1 G4_Si 0 0 40 log_World norot musr/ScintSD 103



############################################################
# 9. VISUALIZATION ATTRIBUTES (OPTIONAL)
############################################################

/musr/command visattributes log_World invisible
/musr/command visattributes log_Target red
/musr/command visattributes log_Det0 yellow
/musr/command visattributes log_Det1 yellow
/musr/command visattributes log_Det2 yellow
/musr/command visattributes log_Det3 yellow



/run/initialize
/control/execute vis.mac

