############################################################
# 0. GENERAL INITIALIZATION
############################################################

/control/verbose 0
/run/verbose 0
/tracking/verbose 0


############################################################
# 1. GEOMETRY
############################################################

# World volume filled with Air
/musr/command construct box World 1000 1000 1500 Air 0 0 0 no_logical_volume norot dead -1



# back streem detectors
/musr/command construct box Det0 20 20 0.05 G4_Si 0 0 -40 log_World norot musr/ScintSD 100
/musr/command construct box Det1 20 20 0.05 G4_Si 0 0 -20 log_World norot musr/ScintSD 101

# Special name Target -> muTarget* variables stored automatically
/musr/command construct tubs Target 0 10 2 0 360 G4_Cu 0 0 0 log_World norot dead 10


/musr/command construct box Det2 20 20 0.05 G4_Si 0 0 20 log_World norot musr/ScintSD 102
/musr/command construct box Det3 20 20 0.05 G4_Si 0 0 40 log_World norot musr/ScintSD 103


############################################################
# 2. PHYSICS CONFIGURATION
############################################################

## Gamma
#/musr/command process addDiscreteProcess gamma G4PhotoElectricEffect
#/musr/command process addDiscreteProcess gamma G4ComptonScattering
## Positrons (from muon decay)
#/musr/command process addProcess e+ G4eMultipleScattering -1 1 1
#/musr/command process addProcess e+ G4eIonisation        -1 2 2
## Muons
#/musr/command process addProcess mu+ G4MuMultipleScattering -1 1 1
#/musr/command process addProcess mu+ G4MuIonisation         -1 2 2
## Optional precision control (Geometry is thin)
#/musr/command process addProcess mu+ G4StepLimiter -1 -1 5

# Gamma
/musr/command process addDiscreteProcess gamma G4PhotoElectricEffect
/musr/command process addDiscreteProcess gamma G4ComptonScattering
/musr/command process addDiscreteProcess gamma G4GammaConversion
/musr/command process addDiscreteProcess gamma G4RayleighScattering

# e-
/musr/command process addProcess         e-    G4eMultipleScattering    -1  1  1
/musr/command process addProcess         e-    G4eIonisation            -1  2  2
/musr/command process addProcess         e-    G4eBremsstrahlung        -1  3  3

# e+
/musr/command process addProcess         e+    G4eMultipleScattering    -1  1  1
/musr/command process addProcess         e+    G4eIonisation            -1  2  2
/musr/command process addProcess         e+    G4eBremsstrahlung        -1  3  3
/musr/command process addProcess         e+    G4eplusAnnihilation       0 -1  4

# mu-
/musr/command process addProcess         mu-   G4MuMultipleScattering   -1  1  1
/musr/command process addProcess         mu-   G4MuIonisation           -1  2  2
/musr/command process addProcess         mu-   G4MuBremsstrahlung       -1  3  3
/musr/command process addProcess         mu-   G4MuPairProduction       -1  4  4

# mu+
/musr/command process addProcess         mu+   G4MuMultipleScattering   -1  1  1
/musr/command process addProcess         mu+   G4MuIonisation           -1  2  2
/musr/command process addProcess         mu+   G4MuBremsstrahlung       -1  3  3
/musr/command process addProcess         mu+   G4MuPairProduction       -1  4  4


############################################################
# 3. OPTIONAL USER LIMITS
############################################################

# Use only if needed.

## /process/msc/StepLimit Minimal | UseDistanceToBoundary | UseSafety 
#/process/msc/StepLimit UseSafety


## Set the overall range cut
#/run/setCut 1 mm

# Set the range cut on a particular volumes (in mm)
#/musr/command SetUserLimits log_Det0 0.1
#/musr/command SetUserLimits log_Det1 0.1
#/musr/command SetUserLimits log_Det2 0.1
#/musr/command SetUserLimits log_Det3 0.1



## Store all events into the ROOT tree or just the interesting ones ? (true is default)
#/musr/command storeOnlyEventsWithHits false
## Set the minimum time separation between two subsequent signals in the same detector (in ns)
#/musr/command signalSeparationTime 0.1


############################################################
# 4. PRIMARY PARTICLE / BEAM
############################################################

# Primary particle
/gun/particle mu+
# Initial position
/gun/position 0 0 -100 mm
# Direction
/gun/direction 0 0 1
#/gun/energy 4.1 MeV
# Beam momentum (mean)
/gun/momentum 28.0 MeV
# Muon spin polarization
/gun/polarization 1 0 0
/gun/muonPolarizFraction 1.0

#/gun/meanarrivaltime 33.33333 microsecond
## Gaussian x/y beam spot, no z smearing
#/gun/vertexsigma 5 5 0 mm

## Beam spot size
## Positive values = Gaussian sigma
## Zero = no smearing
## Negative values = uniform distribution
#/gun/vertexsigma 2 2 0 mm


############################################################
# 5. SENSITIVE DETECTORS
############################################################

#/geom/volume/setSensitive log_Det0 100
#/geom/volume/setSensitive log_Det1 101
#/geom/volume/setSensitive log_Det2 102
#/geom/volume/setSensitive log_Det3 103


############################################################
# 6. EVENT FILTERING
############################################################
# Store only events that hit detector 11 or 12.

#/musr/onlyStoreEventsWithHits 100
#/musr/onlyStoreEventsWithHits 101
#/musr/onlyStoreEventsWithHits 102
#/musr/onlyStoreEventsWithHits 103


############################################################
# 7. ROOT OUTPUT
############################################################

#/musr/command rootOutputDirectoryName data

############################################################
# 8. VISUALIZATION ATTRIBUTES (OPTIONAL)
############################################################

/musr/command visattributes log_World invisible
/musr/command visattributes log_Target red
/musr/command visattributes log_Det0 yellow
/musr/command visattributes log_Det1 yellow
/musr/command visattributes log_Det2 yellow
/musr/command visattributes log_Det3 yellow

/run/initialize

/vis/disable
#/control/execute vis.mac

############################################################
# 9. INITIALIZE AND RUN
############################################################

#/run/initialize
/run/beamOn 100000
/musr/run/howOftenToPrintEvent 10000


