/vis/open OGLIX 1000x800-0+0
/vis/drawVolume
#/vis/viewer/set/style wireframe 
/vis/viewer/set/style surface
/vis/viewer/set/auxiliaryEdge true
/vis/viewer/set/background black
/vis/viewer/set/viewpointThetaPhi 70 30 deg

/vis/scene/add/axes 0 0 0 60 mm

/vis/scene/add/trajectories
/vis/scene/endOfEventAction refresh
#/vis/scene/endOfEventAction  accumulate
/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByParticleID
/vis/scene/add/hits


/vis/viewer/set/autoRefresh true
/vis/viewer/flush

