/musr/command construct box World 300 300 300 G4_AIR 0 0 0 no_logical_volume norot dead -1

#added JSL. Torus piece, Rmin (bore), Rmax (outer), Rtorus (swept), pSPhi (start angle), pDPhi (swept angle)
/musr/command construct torus Tor1 10 20 50 60 200 G4_Al 0 0 0 log_World norot dead 1


/musr/command visattributes log_World invisible
/musr/command visattributes log_Tor1 lightblue


/run/initialize
/control/execute vis.mac
